services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - /home/ochir/projects_2/social_network/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php-fpm:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  postgres:
    image: postgres:13
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    container_name: db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
